'use strict';

const modal = document.querySelector('.modal');
const overlay = document.querySelector('.overlay');
const btnCloseModal = document.querySelector('.close-modal');
//Limitation of querySelector - selects always the first element when the selector/class has multiple elements
// const btnsOpenModal = document.querySelector('.show-modal');
const btnsOpenModal = document.querySelectorAll('.show-modal');

//To alter the styles, export the styles as classes and add/remove corresponding classes from the javascript
const closeModal = function () {
  modal.classList.add('hidden');
  overlay.classList.add('hidden');
};
//read the classList property and can use add/remove to change the appearance of the elements on the web page
const openModal = function () {
  //Each class acts like a container for multiple css properties
  modal.classList.remove('hidden');
  overlay.classList.remove('hidden');
};

for (let i = 0; i < btnsOpenModal.length; i++) {
  //console.log(btnsOpenModal[i].textContent);
  btnsOpenModal[i].addEventListener('click', openModal);
}

//Javascript engine calls the event handler function when exactly the click event happens on this element so no need to use ()
btnCloseModal.addEventListener('click', closeModal);

//When event handlers are used in more than 1 event listeners wrap them into a function and pass this fn as an argument
overlay.addEventListener('click', closeModal);

//Keyboard events are so called global events - because they do not happen on one specific element, we usually listen on the whole document - listening for events every where on the web page - no matter where they occur
document.addEventListener('keydown', function (e) {
  // console.log('Key was pressed',e);
  //Event object is generated by javascript which contains all the information about the event itself - when event occurs javascript engine calls this function with the event object as its argument
  if (e.key === 'Escape' && !modal.classList.contains('hidden')) {
    //key property read on event object
    closeModal();
  }
});

//3 kinds of keyboard events
//keyup - fired when we lift our finger off the keyoard
//keypress - fired when we keep our finger on a certain key
//keydown - fired as soon as we press down the key
